name: Release Charts

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Create
        run: helm create sample
        shell: bash   

      - name: Lint
        run: helm lint  

      - name: Package
        run: helm package sample
        
          
    
