name: Release Charts

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Sonarqube scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: "pheonix-projects"          

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
          context: nest.ravindra.tech  #If left unspecified, current-context from kubeconfig is used as default
        id: setcontext 
      - name: Deploy Sonarqube
        run: kubectl apply -f ${{ github.workspace }}/argocd/sonarqube.yml             
      - name: Login to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: sampleapp
         tags: ${{ github.sha }}
         registry: nexus.ravindra.tech
         dockerfile: app/Dockerfile
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}  
       
      - name: Lint and Package
        run: helm lint sample/ && helm package sample/
      - name: Push
        run: curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} https://nexus.ravindra.tech/repository/nexus-hosted/ --upload-file sample-0.1.0.tgz
        shell: bash




    
